# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Next Build & export

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: [ ubuntu-latest, macos-latest ]

    strategy:
      matrix:
        node-version: [12.19, 14.4]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Cache
      uses: actions/cache@v2.1.2
      with: 
       # A list of files, directories, and wildcard patterns to cache and restore
        path: node_modules
      # An explicit key for restoring and saving the cache
        key:   nodemodules
    
    - run: yarn install
    - run: yarn build
    - run: yarn export
